export const APP_IS_LOADED = 'APP_IS_LOADED';
export const HOME_LOADING = 'HOME_LOADING';
export const FETCH_HOME_LIST = 'FETCH_HOME_LIST';
export const SAVE_POST_DETAILS = 'SAVE_POST_DETAILS';
export const FETCH_COMMENTS_LIST = 'FETCH_COMMENTS_LIST';
export const POST_LOADING = 'POST_LOADING';
export const RESET_COMMENTS = 'RESET_COMMENTS';
